sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install .
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
cache: pip
script: pytest --cov=pyzenodo
after_success:
  - coveralls
notifications:
  email:
    - t.klaver@esciencecenter.nl
